# Generated by Django 4.1.7 on 2023-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("username", models.CharField(max_length=150)),
                ("roster_id", models.CharField(max_length=150)),
                ("roster", models.CharField(max_length=150)),
                ("avatar_id", models.CharField(max_length=150)),
                ("league_name", models.CharField(max_length=150)),
                ("transactions", models.CharField(max_length=150)),
                ("draft_picks", models.CharField(max_length=150)),
                ("recent_trades", models.CharField(max_length=150)),
                ("players", models.CharField(max_length=150)),
                ("matchups", models.CharField(max_length=150)),
                ("record", models.CharField(max_length=150)),
            ],
        ),
    ]
