# Generated by Django 4.1.7 on 2023-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=150)),
                ("username", models.CharField(max_length=150)),
                ("user_password", models.CharField(max_length=150)),
            ],
        ),
    ]
